---
# https://pre-commit.com
default_language_version: {python: python3}
minimum_pre_commit_version: "1.15"

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/klen/pylama
    rev: 8.3.8
    hooks:
      - id: pylama
        args: ["-i", "C901,E203,E501,E722"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: debug-statements
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.1.1
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "88", --preserve-quotes]

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        args: ["-iii", "-lll", "-q"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: text-unicode-replacement-char
      - id: python-no-log-warn

 # checks for pre-commit config
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
